/// Automorphism groups: inner/outer automorphisms, computation,
/// conjugation, and related group-theoretic algorithms for the
/// LITMUS∞ algebraic engine.
///
/// Provides automorphism computation, conjugacy classes, inner/outer
/// automorphism decomposition, characteristic subgroups, automorphism
/// towers, and graph automorphism detection.
#[allow(unused)]

use std::collections::{HashMap, HashSet, BTreeMap, BTreeSet, VecDeque};
use std::fmt;

use super::types::{Permutation, compute_point_orbit, enumerate_from_generators};

// ═══════════════════════════════════════════════════════════════════════════
// FiniteGroup — self-contained group abstraction
// ═══════════════════════════════════════════════════════════════════════════

/// A finite group represented by its elements and Cayley table.
#[derive(Debug, Clone)]
pub struct FiniteGroup {
    /// Elements of the group (as permutations).
    pub elements: Vec<Permutation>,
    /// Cayley table: cayley[i][j] = index of elements[i] * elements[j].
    cayley: Vec<Vec<usize>>,
    /// Index of the identity element.
    identity_idx: usize,
    /// Inverse table: inverses[i] = index of elements[i]^{-1}.
    inverses: Vec<usize>,
    /// Element lookup: maps a permutation to its index.
    element_index: HashMap<Vec<u32>, usize>,
}

impl FiniteGroup {
    /// Create a group from a list of elements.
    pub fn new(elements: Vec<Permutation>) -> Self {
        let n = elements.len();
        let mut element_index = HashMap::new();
        for (i, e) in elements.iter().enumerate() {
            element_index.insert(e.images().to_vec(), i);
        }
        // Build Cayley table
        let mut cayley = vec![vec![0; n]; n];
        for i in 0..n {
            for j in 0..n {
                let product = elements[i].compose(&elements[j]);
                let idx = element_index.get(product.images()).copied().unwrap_or(0);
                cayley[i][j] = idx;
            }
        }
        // Find identity
        let degree = if elements.is_empty() { 0 } else { elements[0].degree() };
        let id = Permutation::identity(degree);
        let identity_idx = element_index.get(&id.images().to_vec()).copied().unwrap_or(0);
        // Build inverse table
        let mut inverses = vec![0; n];
        for i in 0..n {
            let inv = elements[i].inverse();
            inverses[i] = element_index.get(&inv.images().to_vec()).copied().unwrap_or(0);
        }
        Self { elements, cayley, identity_idx, inverses, element_index }
    }

    /// Create from generators by enumerating all products.
    pub fn from_generators(generators: &[Permutation], degree: usize) -> Self {
        let elements: Vec<Permutation> = enumerate_from_generators(generators, degree).into_iter().collect();
        Self::new(elements)
    }

    /// Order of the group.
    pub fn order(&self) -> usize { self.elements.len() }

    /// Get the identity element.
    pub fn identity(&self) -> &Permutation { &self.elements[self.identity_idx] }

    /// Multiply two elements (by index).
    pub fn multiply(&self, i: usize, j: usize) -> usize { self.cayley[i][j] }

    /// Get the inverse of an element (by index).
    pub fn inverse_of(&self, i: usize) -> usize { self.inverses[i] }

    /// Get all elements.
    pub fn get_elements(&self) -> &[Permutation] { &self.elements }

    /// Check if a permutation is in the group.
    pub fn contains(&self, p: &Permutation) -> bool {
        self.element_index.contains_key(&p.images().to_vec())
    }

    /// Get the index of a permutation.
    pub fn index_of(&self, p: &Permutation) -> Option<usize> {
        self.element_index.get(&p.images().to_vec()).copied()
    }

    /// Compute the center Z(G) = { g ∈ G | ∀h. gh = hg }.
    pub fn center(&self) -> Vec<usize> {
        let n = self.order();
        (0..n).filter(|&g| {
            (0..n).all(|h| self.cayley[g][h] == self.cayley[h][g])
        }).collect()
    }

    /// Check if the group is abelian.
    pub fn is_abelian(&self) -> bool {
        self.center().len() == self.order()
    }

    /// Compute a subgroup generated by given element indices.
    pub fn subgroup_generated_by(&self, generators: &[usize]) -> Vec<usize> {
        let mut subgroup: HashSet<usize> = HashSet::new();
        let mut queue: VecDeque<usize> = VecDeque::new();
        subgroup.insert(self.identity_idx);
        queue.push_back(self.identity_idx);
        for &g in generators {
            if subgroup.insert(g) { queue.push_back(g); }
        }
        while let Some(elem) = queue.pop_front() {
            for &gen in generators {
                let product = self.cayley[elem][gen];
                if subgroup.insert(product) { queue.push_back(product); }
                let product_inv = self.cayley[elem][self.inverses[gen]];
                if subgroup.insert(product_inv) { queue.push_back(product_inv); }
            }
        }
        let mut result: Vec<usize> = subgroup.into_iter().collect();
        result.sort();
        result
    }

    /// Check if a set of indices forms a subgroup.
    pub fn is_subgroup(&self, indices: &[usize]) -> bool {
        let set: HashSet<usize> = indices.iter().copied().collect();
        if !set.contains(&self.identity_idx) { return false; }
        for &i in indices {
            if !set.contains(&self.inverses[i]) { return false; }
            for &j in indices {
                if !set.contains(&self.cayley[i][j]) { return false; }
            }
        }
        true
    }

    /// Check if a subgroup is normal: ∀g∈G, ∀h∈H: ghg⁻¹ ∈ H.
    pub fn is_normal_subgroup(&self, subgroup: &[usize]) -> bool {
        let h_set: HashSet<usize> = subgroup.iter().copied().collect();
        let n = self.order();
        for g in 0..n {
            for &h in subgroup {
                let conj = self.cayley[self.cayley[g][h]][self.inverses[g]];
                if !h_set.contains(&conj) { return false; }
            }
        }
        true
    }

    /// Compute the commutator subgroup [G, G].
    pub fn commutator_subgroup(&self) -> Vec<usize> {
        let n = self.order();
        let mut commutators = HashSet::new();
        for g in 0..n {
            for h in 0..n {
                // [g, h] = g h g^{-1} h^{-1}
                let gh = self.cayley[g][h];
                let g_inv_h_inv = self.cayley[self.inverses[g]][self.inverses[h]];
                let comm = self.cayley[gh][g_inv_h_inv];
                commutators.insert(comm);
            }
        }
        let gens: Vec<usize> = commutators.into_iter().collect();
        self.subgroup_generated_by(&gens)
    }
}

impl fmt::Display for FiniteGroup {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Group(order={})", self.order())
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Automorphism
// ═══════════════════════════════════════════════════════════════════════════

/// An automorphism of a finite group: a bijective homomorphism G → G.
#[derive(Debug, Clone)]
pub struct Automorphism {
    /// Mapping: image[i] = index of φ(elements[i]).
    mapping: Vec<usize>,
    /// Inverse mapping.
    inverse_mapping: Vec<usize>,
}

impl Automorphism {
    /// Create a new automorphism from a mapping.
    pub fn new(mapping: Vec<usize>) -> Self {
        let n = mapping.len();
        let mut inverse_mapping = vec![0; n];
        for (i, &j) in mapping.iter().enumerate() {
            inverse_mapping[j] = i;
        }
        Self { mapping, inverse_mapping }
    }

    /// Create the identity automorphism.
    pub fn identity(n: usize) -> Self {
        Self::new((0..n).collect())
    }

    /// Apply the automorphism to an element index.
    pub fn apply(&self, i: usize) -> usize {
        self.mapping[i]
    }

    /// Get the preimage of an element index.
    pub fn preimage(&self, i: usize) -> usize {
        self.inverse_mapping[i]
    }

    /// Compose two automorphisms: (self ∘ other)(x) = self(other(x)).
    pub fn compose(&self, other: &Automorphism) -> Self {
        let n = self.mapping.len();
        let mapping: Vec<usize> = (0..n).map(|i| self.apply(other.apply(i))).collect();
        Self::new(mapping)
    }

    /// Compute the inverse automorphism.
    pub fn inverse(&self) -> Self {
        Self::new(self.inverse_mapping.clone())
    }

    /// Check if this is the identity automorphism.
    pub fn is_identity(&self) -> bool {
        self.mapping.iter().enumerate().all(|(i, &j)| i == j)
    }

    /// Verify that this is a valid automorphism of the group.
    pub fn verify_homomorphism(&self, group: &FiniteGroup) -> bool {
        let n = group.order();
        if self.mapping.len() != n { return false; }
        // Check bijection
        let mut seen = vec![false; n];
        for &j in &self.mapping {
            if j >= n || seen[j] { return false; }
            seen[j] = true;
        }
        // Check homomorphism: φ(ab) = φ(a)φ(b)
        for a in 0..n {
            for b in 0..n {
                let ab = group.multiply(a, b);
                let phi_ab = self.apply(ab);
                let phi_a_phi_b = group.multiply(self.apply(a), self.apply(b));
                if phi_ab != phi_a_phi_b { return false; }
            }
        }
        true
    }

    /// Fixed points of the automorphism.
    pub fn fixed_points(&self) -> Vec<usize> {
        self.mapping.iter().enumerate()
            .filter(|&(i, &j)| i == j)
            .map(|(i, _)| i)
            .collect()
    }

    /// Compute the order of this automorphism.
    pub fn order(&self) -> u64 {
        let id = Self::identity(self.mapping.len());
        let mut current = self.clone();
        let mut ord = 1u64;
        loop {
            if current.is_identity() { return ord; }
            current = current.compose(self);
            ord += 1;
            if ord > self.mapping.len() as u64 * 10 { return ord; }
        }
    }

    /// Get the image as a vector.
    pub fn image(&self) -> &[usize] { &self.mapping }
}

impl PartialEq for Automorphism {
    fn eq(&self, other: &Self) -> bool { self.mapping == other.mapping }
}
impl Eq for Automorphism {}

impl std::hash::Hash for Automorphism {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.mapping.hash(state);
    }
}

impl fmt::Display for Automorphism {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Aut(")?;
        for (i, &j) in self.mapping.iter().enumerate() {
            if i > 0 { write!(f, ",")?; }
            write!(f, "{}→{}", i, j)?;
        }
        write!(f, ")")
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// InnerAutomorphism
// ═══════════════════════════════════════════════════════════════════════════

/// An inner automorphism: conjugation by a group element.
///
/// For a group element g, the inner automorphism φ_g is defined by
/// φ_g(x) = g x g^{-1}.
#[derive(Debug, Clone)]
pub struct InnerAutomorphism {
    /// Index of the conjugating element.
    pub conjugator: usize,
    /// The resulting automorphism.
    pub automorphism: Automorphism,
}

impl InnerAutomorphism {
    /// Create an inner automorphism by conjugation with element g.
    pub fn new(group: &FiniteGroup, g: usize) -> Self {
        let n = group.order();
        let g_inv = group.inverse_of(g);
        let mapping: Vec<usize> = (0..n)
            .map(|x| group.multiply(group.multiply(g, x), g_inv))
            .collect();
        Self {
            conjugator: g,
            automorphism: Automorphism::new(mapping),
        }
    }

    /// Get the automorphism.
    pub fn as_automorphism(&self) -> &Automorphism { &self.automorphism }

    /// Apply the inner automorphism to an element.
    pub fn apply(&self, x: usize) -> usize {
        self.automorphism.apply(x)
    }

    /// Conjugate an element: g x g^{-1}.
    pub fn conjugate(&self, group: &FiniteGroup, x: usize) -> usize {
        let g = self.conjugator;
        let g_inv = group.inverse_of(g);
        group.multiply(group.multiply(g, x), g_inv)
    }

    /// Compute all inner automorphisms of a group.
    pub fn all_inner_automorphisms(group: &FiniteGroup) -> Vec<InnerAutomorphism> {
        let n = group.order();
        let mut seen = HashSet::new();
        let mut result = Vec::new();
        for g in 0..n {
            let inner = InnerAutomorphism::new(group, g);
            if seen.insert(inner.automorphism.mapping.clone()) {
                result.push(inner);
            }
        }
        result
    }
}

/// A conjugacy class in a group.
#[derive(Debug, Clone)]
pub struct ConjugacyClass {
    /// Representative element index.
    pub representative: usize,
    /// All elements in the class.
    pub elements: Vec<usize>,
    /// Size of the centralizer of the representative.
    pub centralizer_order: usize,
}

impl ConjugacyClass {
    /// Size of the class.
    pub fn size(&self) -> usize { self.elements.len() }
}

impl fmt::Display for ConjugacyClass {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Class(rep={}, size={}, |C|={})",
            self.representative, self.elements.len(), self.centralizer_order)
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// OuterAutomorphismGroup
// ═══════════════════════════════════════════════════════════════════════════

/// The outer automorphism group Out(G) = Aut(G) / Inn(G).
#[derive(Debug, Clone)]
pub struct OuterAutomorphismGroup {
    /// Coset representatives of Inn(G) in Aut(G).
    pub coset_representatives: Vec<Automorphism>,
    /// Order of Out(G).
    pub order: usize,
}

impl OuterAutomorphismGroup {
    /// Compute Out(G) from the full automorphism group and inner automorphisms.
    pub fn compute(all_auts: &[Automorphism], inner_auts: &[Automorphism]) -> Self {
        let inner_set: HashSet<Vec<usize>> = inner_auts.iter()
            .map(|a| a.mapping.clone())
            .collect();
        let mut coset_reps = Vec::new();
        let mut seen_cosets: HashSet<Vec<usize>> = HashSet::new();
        for aut in all_auts {
            // Compute the coset aut * Inn(G) and check if we've seen it
            let mut coset_key = Vec::new();
            for inner in inner_auts {
                let composed = aut.compose(inner);
                let mut key = composed.mapping.clone();
                key.sort();
                coset_key.extend(key);
            }
            if seen_cosets.insert(coset_key) {
                coset_reps.push(aut.clone());
            }
        }
        let order = coset_reps.len();
        Self { coset_representatives: coset_reps, order }
    }

    /// Check if an automorphism is outer (not inner).
    pub fn is_outer(aut: &Automorphism, inner_auts: &[Automorphism]) -> bool {
        !inner_auts.iter().any(|inner| inner.mapping == aut.mapping)
    }

    /// Get the order of Out(G).
    pub fn outer_order(&self) -> usize { self.order }
}

// ═══════════════════════════════════════════════════════════════════════════
// AutomorphismGroup
// ═══════════════════════════════════════════════════════════════════════════

/// The full automorphism group Aut(G) of a finite group G.
#[derive(Debug, Clone)]
pub struct AutomorphismGroup {
    /// All automorphisms.
    pub automorphisms: Vec<Automorphism>,
    /// Order of Aut(G).
    pub order: usize,
    /// Inner automorphism subgroup (as indices into automorphisms).
    pub inner_indices: Vec<usize>,
}

impl AutomorphismGroup {
    /// Compute the full automorphism group of a finite group.
    ///
    /// Uses brute-force enumeration for small groups.
    pub fn compute(group: &FiniteGroup) -> Self {
        let n = group.order();
        if n == 0 {
            return Self { automorphisms: Vec::new(), order: 0, inner_indices: Vec::new() };
        }
        // For small groups, enumerate all bijections that are homomorphisms
        let mut automorphisms = Vec::new();
        if n <= 12 {
            // Try all permutations of elements
            let mut perm: Vec<usize> = (0..n).collect();
            loop {
                let aut = Automorphism::new(perm.clone());
                if aut.verify_homomorphism(group) {
                    automorphisms.push(aut);
                }
                if !next_permutation(&mut perm) { break; }
            }
        } else {
            // For larger groups, use inner automorphisms as a starting point
            let inners = InnerAutomorphism::all_inner_automorphisms(group);
            for inner in &inners {
                automorphisms.push(inner.automorphism.clone());
            }
        }
        // Find inner automorphisms
        let inner_auts: Vec<Automorphism> = InnerAutomorphism::all_inner_automorphisms(group)
            .into_iter().map(|i| i.automorphism).collect();
        let inner_set: HashSet<Vec<usize>> = inner_auts.iter()
            .map(|a| a.mapping.clone()).collect();
        let inner_indices: Vec<usize> = automorphisms.iter().enumerate()
            .filter(|(_, a)| inner_set.contains(&a.mapping))
            .map(|(i, _)| i)
            .collect();
        let order = automorphisms.len();
        Self { automorphisms, order, inner_indices }
    }

    /// Get all automorphisms.
    pub fn generators(&self) -> &[Automorphism] { &self.automorphisms }

    /// Get the order.
    pub fn order(&self) -> usize { self.order }

    /// Check if an automorphism is in the group.
    pub fn is_member(&self, aut: &Automorphism) -> bool {
        self.automorphisms.iter().any(|a| a.mapping == aut.mapping)
    }

    /// Get the inner subgroup.
    pub fn inner_subgroup(&self) -> Vec<&Automorphism> {
        self.inner_indices.iter().map(|&i| &self.automorphisms[i]).collect()
    }

    /// Compute the outer quotient.
    pub fn outer_quotient(&self) -> OuterAutomorphismGroup {
        let inner_auts: Vec<Automorphism> = self.inner_indices.iter()
            .map(|&i| self.automorphisms[i].clone())
            .collect();
        OuterAutomorphismGroup::compute(&self.automorphisms, &inner_auts)
    }

    /// Check if the group is complete (Out(G) is trivial and Z(G) is trivial).
    pub fn is_complete(&self, group: &FiniteGroup) -> bool {
        let outer = self.outer_quotient();
        let center = group.center();
        outer.order == 1 && center.len() == 1
    }
}

/// Compute the next permutation in lexicographic order.
fn next_permutation(perm: &mut Vec<usize>) -> bool {
    let n = perm.len();
    if n <= 1 { return false; }
    let mut i = n - 1;
    while i > 0 && perm[i - 1] >= perm[i] { i -= 1; }
    if i == 0 { return false; }
    let mut j = n - 1;
    while perm[j] <= perm[i - 1] { j -= 1; }
    perm.swap(i - 1, j);
    perm[i..].reverse();
    true
}

// ═══════════════════════════════════════════════════════════════════════════
// ConjugationEngine
// ═══════════════════════════════════════════════════════════════════════════

/// Engine for conjugation operations and conjugacy-related computations.
#[derive(Debug, Clone)]
pub struct ConjugationEngine {
    /// Reference to the group.
    group_elements: Vec<Permutation>,
    /// Cayley table for fast multiplication.
    cayley: Vec<Vec<usize>>,
    /// Inverse table.
    inverses: Vec<usize>,
}

impl ConjugationEngine {
    /// Create from a FiniteGroup.
    pub fn from_group(group: &FiniteGroup) -> Self {
        Self {
            group_elements: group.elements.clone(),
            cayley: group.cayley.clone(),
            inverses: group.inverses.clone(),
        }
    }

    /// Conjugate x by g: g x g^{-1}.
    pub fn conjugate(&self, g: usize, x: usize) -> usize {
        self.cayley[self.cayley[g][x]][self.inverses[g]]
    }

    /// Check if two elements are conjugate.
    pub fn are_conjugate(&self, a: usize, b: usize) -> bool {
        let n = self.group_elements.len();
        (0..n).any(|g| self.conjugate(g, a) == b)
    }

    /// Compute all conjugacy classes.
    pub fn conjugacy_classes(&self) -> Vec<ConjugacyClass> {
        let n = self.group_elements.len();
        let mut assigned = vec![false; n];
        let mut classes = Vec::new();
        for rep in 0..n {
            if assigned[rep] { continue; }
            let mut class = Vec::new();
            for g in 0..n {
                let conj = self.conjugate(g, rep);
                if !assigned[conj] {
                    assigned[conj] = true;
                    class.push(conj);
                }
            }
            class.sort();
            class.dedup();
            let centralizer_order = n / class.len();
            classes.push(ConjugacyClass {
                representative: rep,
                elements: class,
                centralizer_order,
            });
        }
        classes
    }

    /// Compute the class equation: |G| = |Z(G)| + Σ [G : C_G(x_i)].
    pub fn class_equation(&self) -> Vec<usize> {
        self.conjugacy_classes().iter().map(|c| c.size()).collect()
    }

    /// Compute the centralizer of an element: C_G(x) = { g | gx = xg }.
    pub fn centralizer(&self, x: usize) -> Vec<usize> {
        let n = self.group_elements.len();
        (0..n).filter(|&g| self.cayley[g][x] == self.cayley[x][g]).collect()
    }

    /// Compute the normalizer of a subgroup H: N_G(H) = { g | gHg^{-1} = H }.
    pub fn normalizer(&self, subgroup: &[usize]) -> Vec<usize> {
        let n = self.group_elements.len();
        let h_set: HashSet<usize> = subgroup.iter().copied().collect();
        (0..n).filter(|&g| {
            subgroup.iter().all(|&h| {
                let conj = self.conjugate(g, h);
                h_set.contains(&conj)
            })
        }).collect()
    }

    /// Compute the conjugation action as a permutation representation.
    pub fn conjugation_action(&self, g: usize) -> Vec<usize> {
        let n = self.group_elements.len();
        (0..n).map(|x| self.conjugate(g, x)).collect()
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// CharacteristicSubgroup
// ═══════════════════════════════════════════════════════════════════════════

/// Detector and verifier for characteristic subgroups.
#[derive(Debug, Clone)]
pub struct CharacteristicSubgroupFinder {
    /// The group.
    group: FiniteGroup,
    /// All automorphisms.
    automorphisms: Vec<Automorphism>,
}

impl CharacteristicSubgroupFinder {
    /// Create a new finder.
    pub fn new(group: FiniteGroup, automorphisms: Vec<Automorphism>) -> Self {
        Self { group, automorphisms }
    }

    /// Check if a subgroup is characteristic (fixed by all automorphisms).
    pub fn is_characteristic(&self, subgroup: &[usize]) -> bool {
        let h_set: HashSet<usize> = subgroup.iter().copied().collect();
        self.automorphisms.iter().all(|aut| {
            subgroup.iter().all(|&h| h_set.contains(&aut.apply(h)))
        })
    }

    /// Find all characteristic subgroups.
    pub fn find_characteristic_subgroups(&self) -> Vec<Vec<usize>> {
        let n = self.group.order();
        let mut result = Vec::new();
        // Try all subsets that form subgroups
        // For small groups, use brute force
        if n <= 16 {
            for mask in 0..(1u64 << n) {
                let subset: Vec<usize> = (0..n).filter(|&i| mask & (1u64 << i) != 0).collect();
                if self.group.is_subgroup(&subset) && self.is_characteristic(&subset) {
                    result.push(subset);
                }
            }
        } else {
            // For larger groups, check known characteristic subgroups
            let center = self.group.center();
            if self.is_characteristic(&center) { result.push(center); }
            let comm = self.group.commutator_subgroup();
            if self.is_characteristic(&comm) { result.push(comm); }
        }
        result
    }

    /// Get the center (always characteristic).
    pub fn center(&self) -> Vec<usize> { self.group.center() }

    /// Get the commutator subgroup (always characteristic).
    pub fn commutator_subgroup(&self) -> Vec<usize> { self.group.commutator_subgroup() }

    /// Compute the Frattini subgroup: intersection of all maximal subgroups.
    pub fn frattini_subgroup(&self) -> Vec<usize> {
        let n = self.group.order();
        let maximal = self.find_maximal_subgroups();
        if maximal.is_empty() {
            return (0..n).collect(); // entire group
        }
        let mut intersection: HashSet<usize> = maximal[0].iter().copied().collect();
        for sub in &maximal[1..] {
            let sub_set: HashSet<usize> = sub.iter().copied().collect();
            intersection = intersection.intersection(&sub_set).copied().collect();
        }
        let mut result: Vec<usize> = intersection.into_iter().collect();
        result.sort();
        result
    }

    /// Find maximal subgroups.
    fn find_maximal_subgroups(&self) -> Vec<Vec<usize>> {
        let n = self.group.order();
        let mut subgroups = Vec::new();
        if n <= 16 {
            for mask in 1..(1u64 << n) - 1 {
                let subset: Vec<usize> = (0..n).filter(|&i| mask & (1u64 << i) != 0).collect();
                if subset.len() < n && self.group.is_subgroup(&subset) {
                    subgroups.push(subset);
                }
            }
        }
        // Filter to maximal ones
        let mut maximal = Vec::new();
        for (i, sub) in subgroups.iter().enumerate() {
            let sub_set: HashSet<usize> = sub.iter().copied().collect();
            let is_maximal = !subgroups.iter().enumerate().any(|(j, other)| {
                j != i && other.len() > sub.len() && sub.iter().all(|x| other.contains(x))
            });
            if is_maximal { maximal.push(sub.clone()); }
        }
        maximal
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// AutomorphismTower
// ═══════════════════════════════════════════════════════════════════════════

/// The automorphism tower of a group: G → Aut(G) → Aut(Aut(G)) → ...
#[derive(Debug, Clone)]
pub struct AutomorphismTower {
    /// Orders of the groups in the tower.
    pub tower_orders: Vec<usize>,
    /// Whether the tower stabilizes.
    pub stabilized: bool,
    /// Height at which stabilization occurs.
    pub stable_height: Option<usize>,
}

impl AutomorphismTower {
    /// Compute the automorphism tower up to a maximum height.
    pub fn compute(group: &FiniteGroup, max_height: usize) -> Self {
        let mut tower_orders = vec![group.order()];
        let mut current_group = group.clone();
        for h in 0..max_height {
            let aut_group = AutomorphismGroup::compute(&current_group);
            tower_orders.push(aut_group.order);
            // Check stabilization
            if aut_group.order == current_group.order() {
                return Self {
                    tower_orders,
                    stabilized: true,
                    stable_height: Some(h + 1),
                };
            }
            // Build the next group from automorphisms
            if aut_group.order > 20 { break; }
            // Convert automorphisms to permutations for the next level
            let degree = aut_group.order;
            let perms: Vec<Permutation> = aut_group.automorphisms.iter().enumerate().map(|(i, _)| {
                let images: Vec<u32> = (0..degree).map(|j| {
                    // Cayley representation: left multiplication
                    let composed = aut_group.automorphisms[i].compose(&aut_group.automorphisms[j]);
                    aut_group.automorphisms.iter().position(|a| a.mapping == composed.mapping)
                        .unwrap_or(0) as u32
                }).collect();
                Permutation::new(images)
            }).collect();
            current_group = FiniteGroup::new(perms);
        }
        Self {
            tower_orders,
            stabilized: false,
            stable_height: None,
        }
    }

    /// Height of the tower (number of levels computed).
    pub fn height(&self) -> usize { self.tower_orders.len() }

    /// Check if the tower stabilizes (group is complete).
    pub fn is_complete(&self) -> bool { self.stabilized }
}

// ═══════════════════════════════════════════════════════════════════════════
// GraphAutomorphism
// ═══════════════════════════════════════════════════════════════════════════

/// Automorphisms of a colored graph.
#[derive(Debug, Clone)]
pub struct GraphAutomorphism {
    /// Number of vertices.
    n: usize,
    /// Adjacency matrix.
    adj: Vec<Vec<bool>>,
    /// Vertex colors.
    colors: Vec<u32>,
    /// Computed automorphisms (as permutations of vertices).
    automorphisms: Vec<Permutation>,
}

impl GraphAutomorphism {
    /// Create from an adjacency matrix and optional colors.
    pub fn new(adj: Vec<Vec<bool>>, colors: Option<Vec<u32>>) -> Self {
        let n = adj.len();
        let colors = colors.unwrap_or_else(|| vec![0; n]);
        Self { n, adj, colors, automorphisms: Vec::new() }
    }

    /// Create from a list of edges.
    pub fn from_edges(n: usize, edges: &[(usize, usize)]) -> Self {
        let mut adj = vec![vec![false; n]; n];
        for &(u, v) in edges {
            adj[u][v] = true;
            adj[v][u] = true;
        }
        Self::new(adj, None)
    }

    /// Compute automorphisms using simple refinement.
    pub fn compute_automorphisms(&mut self) -> &[Permutation] {
        self.automorphisms.clear();
        // Identity is always an automorphism
        self.automorphisms.push(Permutation::identity(self.n));
        if self.n <= 8 {
            // Brute force for small graphs
            let mut perm: Vec<u32> = (0..self.n as u32).collect();
            loop {
                let p = Permutation::new(perm.clone());
                if self.is_automorphism(&p) && !p.is_identity() {
                    self.automorphisms.push(p);
                }
                if !next_perm_u32(&mut perm) { break; }
            }
        } else {
            // Use color refinement to find candidate automorphisms
            let refined = self.color_refinement();
            // Group vertices by refined color
            let mut color_groups: HashMap<u32, Vec<usize>> = HashMap::new();
            for (v, &c) in refined.iter().enumerate() {
                color_groups.entry(c).or_default().push(v);
            }
            // Try swaps within color classes
            for (_color, group) in &color_groups {
                if group.len() > 1 {
                    for i in 0..group.len() {
                        for j in (i + 1)..group.len() {
                            let mut images: Vec<u32> = (0..self.n as u32).collect();
                            images[group[i]] = group[j] as u32;
                            images[group[j]] = group[i] as u32;
                            let p = Permutation::new(images);
                            if self.is_automorphism(&p) {
                                self.automorphisms.push(p);
                            }
                        }
                    }
                }
            }
        }
        &self.automorphisms
    }

    /// Check if a permutation is an automorphism of the graph.
    pub fn is_automorphism(&self, p: &Permutation) -> bool {
        // Check color preservation
        for v in 0..self.n {
            if self.colors[v] != self.colors[p.apply(v as u32) as usize] {
                return false;
            }
        }
        // Check edge preservation
        for u in 0..self.n {
            for v in 0..self.n {
                let pu = p.apply(u as u32) as usize;
                let pv = p.apply(v as u32) as usize;
                if self.adj[u][v] != self.adj[pu][pv] {
                    return false;
                }
            }
        }
        true
    }

    /// Compute the canonical form of the graph.
    pub fn canonical_form(&self) -> Vec<Vec<bool>> {
        let refined = self.color_refinement();
        // Sort vertices by refined color, then relabel
        let mut sorted: Vec<usize> = (0..self.n).collect();
        sorted.sort_by_key(|&v| refined[v]);
        let mut relabel = vec![0usize; self.n];
        for (new, &old) in sorted.iter().enumerate() {
            relabel[old] = new;
        }
        let mut canon = vec![vec![false; self.n]; self.n];
        for u in 0..self.n {
            for v in 0..self.n {
                canon[relabel[u]][relabel[v]] = self.adj[u][v];
            }
        }
        canon
    }

    /// Check if two graphs are isomorphic.
    pub fn is_isomorphic(&self, other: &GraphAutomorphism) -> bool {
        if self.n != other.n { return false; }
        self.canonical_form() == other.canonical_form()
    }

    /// Compute orbit partition of vertices under the automorphism group.
    pub fn orbit_partition(&self) -> Vec<Vec<usize>> {
        let mut parent: Vec<usize> = (0..self.n).collect();
        fn find(parent: &mut Vec<usize>, x: usize) -> usize {
            if parent[x] != x { parent[x] = find(parent, parent[x]); }
            parent[x]
        }
        fn union(parent: &mut Vec<usize>, x: usize, y: usize) {
            let px = find(parent, x);
            let py = find(parent, y);
            if px != py { parent[px] = py; }
        }
        for aut in &self.automorphisms {
            for v in 0..self.n {
                union(&mut parent, v, aut.apply(v as u32) as usize);
            }
        }
        let mut orbits: HashMap<usize, Vec<usize>> = HashMap::new();
        for v in 0..self.n {
            orbits.entry(find(&mut parent, v)).or_default().push(v);
        }
        orbits.into_values().collect()
    }

    /// Color refinement (1-WL) algorithm.
    fn color_refinement(&self) -> Vec<u32> {
        let mut colors = self.colors.clone();
        loop {
            let mut new_colors = vec![0u32; self.n];
            let mut color_map: HashMap<(u32, Vec<u32>), u32> = HashMap::new();
            let mut next_color = 0u32;
            for v in 0..self.n {
                let mut neighbor_colors: Vec<u32> = (0..self.n)
                    .filter(|&u| self.adj[v][u])
                    .map(|u| colors[u])
                    .collect();
                neighbor_colors.sort();
                let key = (colors[v], neighbor_colors);
                let c = *color_map.entry(key).or_insert_with(|| {
                    let c = next_color;
                    next_color += 1;
                    c
                });
                new_colors[v] = c;
            }
            if new_colors == colors { break; }
            colors = new_colors;
        }
        colors
    }

    /// Get the computed automorphisms.
    pub fn get_automorphisms(&self) -> &[Permutation] { &self.automorphisms }

    /// Number of automorphisms found.
    pub fn automorphism_count(&self) -> usize { self.automorphisms.len() }
}

/// Next permutation for u32 vec.
fn next_perm_u32(perm: &mut Vec<u32>) -> bool {
    let n = perm.len();
    if n <= 1 { return false; }
    let mut i = n - 1;
    while i > 0 && perm[i - 1] >= perm[i] { i -= 1; }
    if i == 0 { return false; }
    let mut j = n - 1;
    while perm[j] <= perm[i - 1] { j -= 1; }
    perm.swap(i - 1, j);
    perm[i..].reverse();
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cyclic_group(n: usize) -> FiniteGroup {
        let gen = Permutation::new((1..n as u32).chain(std::iter::once(0)).collect());
        FiniteGroup::from_generators(&[gen], n)
    }

    #[test]
    fn test_cyclic_group() {
        let g = cyclic_group(4);
        assert_eq!(g.order(), 4);
        assert!(g.is_abelian());
    }

    #[test]
    fn test_inner_automorphisms() {
        let g = cyclic_group(3);
        let inners = InnerAutomorphism::all_inner_automorphisms(&g);
        // Cyclic groups are abelian, so all inner auts are identity
        assert_eq!(inners.len(), 1);
    }

    #[test]
    fn test_automorphism_verify() {
        let g = cyclic_group(3);
        let id = Automorphism::identity(g.order());
        assert!(id.verify_homomorphism(&g));
        assert!(id.is_identity());
    }

    #[test]
    fn test_conjugacy_classes() {
        let g = cyclic_group(4);
        let engine = ConjugationEngine::from_group(&g);
        let classes = engine.conjugacy_classes();
        // Abelian group: each element is its own conjugacy class
        assert_eq!(classes.len(), 4);
    }

    #[test]
    fn test_graph_automorphism() {
        // Complete graph K3 has 6 automorphisms (S3)
        let mut ga = GraphAutomorphism::from_edges(3, &[(0,1),(1,2),(0,2)]);
        ga.compute_automorphisms();
        assert_eq!(ga.automorphism_count(), 6);
    }
}
